/*!
 * i18nkey.ts
 *
 * !! DO NOT MODIFY !!
 *  This file is generated by the 'cdp-task i18n genkey'.
 *
 * Created Date: 2024-06-04T07:47:06.786Z
 */

export const i18nKey = {
    'app': {
        'name': 'app.name',
        'common': {
            'control': {
                'back': 'app.common.control.back',
                'reload': 'app.common.control.reload'
            },
            'message': {
                'listview': {
                    'loadComplete': 'app.common.message.listview.loadComplete'
                }
            },
            'navigateTo': {
                'settings': 'app.common.navigateTo.settings'
            }
        },
        'pageRoot': {
            'title': 'app.pageRoot.title',
            'category': {
                'class': 'app.pageRoot.category.class'
            },
            'navigateTo': {
                'simpleListClass': 'app.pageRoot.navigateTo.simpleListClass',
                'expandListClass': 'app.pageRoot.navigateTo.expandListClass'
            }
        },
        'pageSimpleListClass': {
            'title': 'app.pageSimpleListClass.title',
            'description': 'app.pageSimpleListClass.description'
        },
        'pageExpandListClass': {
            'title': 'app.pageExpandListClass.title',
            'description': 'app.pageExpandListClass.description',
            'control': {
                'expandAll': 'app.pageExpandListClass.control.expandAll',
                'collapseAll': 'app.pageExpandListClass.control.collapseAll'
            }
        },
        'pageSettings': {
            'title': 'app.pageSettings.title',
            'refresh': {
                'title': 'app.pageSettings.refresh.title',
                'lv1': 'app.pageSettings.refresh.lv1',
                'lv2': 'app.pageSettings.refresh.lv2'
            },
            'transition': {
                'title': 'app.pageSettings.transition.title'
            },
            'language': {
                'title': 'app.pageSettings.language.title',
                'ja': 'app.pageSettings.language.ja',
                'en': 'app.pageSettings.language.en'
            }
        }
    }
};
