/*!
 * i18nkey.ts
 *
 * !! DO NOT MODIFY !!
 *  This file is generated by the 'cdp-task i18n genkey'.
 *
 * Created Date: 2024-05-29T10:38:57.242Z
 */

export const i18nKey = {
    'app': {
        'name': 'app.name',
        'common': {
            'back': 'app.common.back',
            'reload': 'app.common.reload'
        },
        'pageRoot': {
            'title': 'app.pageRoot.title',
            'navigateTo': {
                'settings': 'app.pageRoot.navigateTo.settings'
            }
        },
        'pageSettings': {
            'title': 'app.pageSettings.title',
            'refresh': {
                'title': 'app.pageSettings.refresh.title',
                'lv1': 'app.pageSettings.refresh.lv1',
                'lv2': 'app.pageSettings.refresh.lv2'
            },
            'transition': {
                'title': 'app.pageSettings.transition.title'
            },
            'language': {
                'title': 'app.pageSettings.language.title',
                'ja': 'app.pageSettings.language.ja',
                'en': 'app.pageSettings.language.en'
            }
        }
    }
};
