/*!
 * i18nkey.ts
 *
 * !! DO NOT MODIFY !!
 *  This file is generated by the 'cdp-task i18n genkey'.
 *
 * Created Date: 2024-05-28T12:51:54.706Z
 */

export const i18nKey = {
    'app': {
        'name': 'app.name',
        'common': {
            'back': 'app.common.back',
            'reload': 'app.common.reload'
        }
    }
};
