/*!
 * i18nkey.ts
 *
 * !! DO NOT MODIFY !!
 *  This file is generated by the 'cdp-task i18n genkey'.
 *
 * Created Date: 2023-03-28T10:44:25.365Z
 */

export const i18nKey = {
    'app': {
        'common': {
            'back': 'app.common.back',
            'reload': 'app.common.reload'
        },
        'navigateTo': {
            'class': 'app.navigateTo.class',
            'factory': 'app.navigateTo.factory',
            'pageView': 'app.navigateTo.pageView'
        },
        'pageRoot': {
            'title': 'app.pageRoot.title'
        },
        'pageClass': {
            'title': 'app.pageClass.title',
            'refresh': {
                'title': 'app.pageClass.refresh.title',
                'lv1': 'app.pageClass.refresh.lv1',
                'lv2': 'app.pageClass.refresh.lv2'
            },
            'transition': {
                'title': 'app.pageClass.transition.title'
            },
            'language': {
                'title': 'app.pageClass.language.title',
                'ja': 'app.pageClass.language.ja',
                'en': 'app.pageClass.language.en'
            }
        },
        'pageView': {
            'title': 'app.pageView.title',
            'toSubflow': 'app.pageView.toSubflow'
        },
        'subflow': {
            'title': {
                'pageA-normal': 'app.subflow.title.pageA-normal',
                'pageA-subflow': 'app.subflow.title.pageA-subflow',
                'pageB-normal': 'app.subflow.title.pageB-normal',
                'pageB-subflow': 'app.subflow.title.pageB-subflow',
                'pageC': 'app.subflow.title.pageC'
            },
            'description': {
                'pageA-normal': 'app.subflow.description.pageA-normal',
                'pageA-subflow': 'app.subflow.description.pageA-subflow',
                'pageB-normal': 'app.subflow.description.pageB-normal',
                'pageB-subflow': 'app.subflow.description.pageB-subflow',
                'pageC': 'app.subflow.description.pageC'
            },
            'button': {
                'toPageB-normal': 'app.subflow.button.toPageB-normal',
                'toPageB-subflow': 'app.subflow.button.toPageB-subflow',
                'beginSubFlowDestA': 'app.subflow.button.beginSubFlowDestA',
                'beginSubFlowDestB': 'app.subflow.button.beginSubFlowDestB',
                'beginSubFlowDestC': 'app.subflow.button.beginSubFlowDestC',
                'endSubFlow': 'app.subflow.button.endSubFlow'
            }
        }
    }
};
