/*!
 * i18nkey.ts
 *
 * !! DO NOT MODIFY !!
 *  This file is generated by the 'cdp-task i18n genkey'.
 *
 * Created Date: 2023-04-26T01:21:17.488Z
 */

export const i18nKey = {
    'app': {
        'common': {
            'back': 'app.common.back',
            'reload': 'app.common.reload'
        },
        'navigateTo': {
            'class': 'app.navigateTo.class',
            'factory': 'app.navigateTo.factory',
            'pageView': 'app.navigateTo.pageView',
            'settings': 'app.navigateTo.settings'
        },
        'pageRoot': {
            'title': 'app.pageRoot.title'
        },
        'pageClass': {
            'title': 'app.pageClass.title',
            'refresh': {
                'title': 'app.pageClass.refresh.title',
                'lv1': 'app.pageClass.refresh.lv1',
                'lv2': 'app.pageClass.refresh.lv2'
            },
            'transition': {
                'title': 'app.pageClass.transition.title'
            },
            'language': {
                'title': 'app.pageClass.language.title',
                'ja': 'app.pageClass.language.ja',
                'en': 'app.pageClass.language.en'
            }
        },
        'pageView': {
            'title': 'app.pageView.title',
            'functions': {
                'description': 'app.pageView.functions.description',
                'to': {
                    'subflow': 'app.pageView.functions.to.subflow',
                    'template': 'app.pageView.functions.to.template'
                }
            }
        },
        'subflow': {
            'title': {
                'pageA-normal': 'app.subflow.title.pageA-normal',
                'pageA-subflow': 'app.subflow.title.pageA-subflow',
                'pageB-normal': 'app.subflow.title.pageB-normal',
                'pageB-subflow': 'app.subflow.title.pageB-subflow',
                'pageC': 'app.subflow.title.pageC'
            },
            'description': {
                'pageA-normal': 'app.subflow.description.pageA-normal',
                'pageA-subflow': 'app.subflow.description.pageA-subflow',
                'pageB-normal': 'app.subflow.description.pageB-normal',
                'pageB-subflow': 'app.subflow.description.pageB-subflow',
                'pageC': 'app.subflow.description.pageC'
            },
            'button': {
                'toPageB-normal': 'app.subflow.button.toPageB-normal',
                'toPageB-subflow': 'app.subflow.button.toPageB-subflow',
                'beginSubFlowDestA': 'app.subflow.button.beginSubFlowDestA',
                'beginSubFlowDestB': 'app.subflow.button.beginSubFlowDestB',
                'beginSubFlowDestC': 'app.subflow.button.beginSubFlowDestC',
                'endSubFlow': 'app.subflow.button.endSubFlow'
            }
        },
        'template': {
            'root': {
                'title': 'app.template.root.title',
                'description': 'app.template.root.description',
                'type': {
                    'single': 'app.template.root.type.single',
                    'composite': 'app.template.root.type.composite'
                },
                'navigateTo': {
                    'mustache': 'app.template.root.navigateTo.mustache',
                    'mustache-bridge': 'app.template.root.navigateTo.mustache-bridge',
                    'stampino-bridge': 'app.template.root.navigateTo.stampino-bridge',
                    'template-literal': 'app.template.root.navigateTo.template-literal',
                    'component-view': 'app.template.root.navigateTo.component-view',
                    'component-custom': 'app.template.root.navigateTo.component-custom',
                    'component-function': 'app.template.root.navigateTo.component-function'
                }
            },
            'mustache': {
                'title': 'app.template.mustache.title',
                'description': 'app.template.mustache.description',
                'input': {
                    'description': 'app.template.mustache.input.description'
                }
            },
            'mustache-bridge': {
                'title': 'app.template.mustache-bridge.title',
                'description': 'app.template.mustache-bridge.description',
                'input': {
                    'description': 'app.template.mustache-bridge.input.description'
                }
            },
            'stampino-bridge': {
                'title': 'app.template.stampino-bridge.title',
                'description': 'app.template.stampino-bridge.description'
            },
            'template-literal': {
                'title': 'app.template.template-literal.title',
                'description': 'app.template.template-literal.description'
            },
            'component-view': {
                'title': 'app.template.component-view.title',
                'description': 'app.template.component-view.description',
                'input': {
                    'description': 'app.template.component-view.input.description'
                }
            },
            'component-custom': {
                'title': 'app.template.component-custom.title',
                'description': 'app.template.component-custom.description'
            },
            'component-function': {
                'title': 'app.template.component-function.title',
                'description': 'app.template.component-function.description'
            },
            'content': {
                'state': {
                    'label': 'app.template.content.state.label',
                    'button': {
                        'reset': 'app.template.content.state.button.reset'
                    }
                },
                'effect': {
                    'label': 'app.template.content.effect.label',
                    'button': {
                        'label': 'app.template.content.effect.button.label'
                    }
                },
                'interval': {
                    'label': 'app.template.content.interval.label',
                    'button': {
                        'start': 'app.template.content.interval.button.start',
                        'stop': 'app.template.content.interval.button.stop'
                    }
                },
                'input': {
                    'label': 'app.template.content.input.label',
                    'placeholder': 'app.template.content.input.placeholder'
                },
                'list': {
                    'label': 'app.template.content.list.label',
                    'column': {
                        'id': 'app.template.content.list.column.id',
                        'score': 'app.template.content.list.column.score'
                    },
                    'button': {
                        'clear': 'app.template.content.list.button.clear'
                    },
                    'noItem': 'app.template.content.list.noItem'
                }
            }
        }
    }
};
