/*!
 * i18nkey.ts
 *
 * !! DO NOT MODIFY !!
 *  This file is generated by the 'cdp-task i18n genkey'.
 *
 * Created Date: 2023-03-19T10:01:38.953Z
 */

export const i18nKey = {
    'app': {
        'common': {
            'back': 'app.common.back',
            'reload': 'app.common.reload'
        },
        'navigateTo': {
            'class': 'app.navigateTo.class',
            'factory': 'app.navigateTo.factory',
            'pageView': 'app.navigateTo.pageView'
        },
        'pageRoot': {
            'title': 'app.pageRoot.title'
        },
        'pageClass': {
            'title': 'app.pageClass.title',
            'refresh': {
                'title': 'app.pageClass.refresh.title',
                'lv1': 'app.pageClass.refresh.lv1',
                'lv2': 'app.pageClass.refresh.lv2'
            },
            'language': {
                'title': 'app.pageClass.language.title',
                'ja': 'app.pageClass.language.ja',
                'en': 'app.pageClass.language.en'
            }
        }
    },
    'EOF': 'EOF'
};
